language: java
cache:
  directories:
  - $HOME/.jdk
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - curl -s https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh | bash /dev/stdin mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pfast
script:
  - curl -s https://raw.githubusercontent.com/vjkoskela/jdk-wrapper/master/jdk-wrapper.sh | bash /dev/stdin mvn clean install -Pfast
  - mvn clean
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
    - JDKW_VERSION=8u74
    - JDKW_BUILD=b02
jdk:
  - oraclejdk8
