language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install -Pfast
  - mvn clean
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
